### ISSUE TITLE
No confirmation received for placed order, but order placed

### ISSUE THREAD

**Issue by justinammerlaan** [JKorf/Bitfinex.Net#23] opened 2018-06-05 23:01 UTC
Randomly i receive the error 'No confirmation received for placed order'. When i go to the exchange, the order is actually placed.

**Comment by JKorf** [comment] 2018-06-06 07:44
Hi, do you have any logging of when this happens? Could you reproduce this with debug log verbosity?

**Comment by justinammerlaan** [comment] 2018-06-06 17:41
I believe it occurs when there is an issue with the order. In this case, the order amount is invalid, however bitfinex still accept the order. There is a response regarding the order but an error is not raised.

2018-06-06 10:37:19:168 | Info | Going to place order
2018-06-06 10:37:19:188 | Debug | Sending [0,"on",null,{"type":"STOP","symbol":"tBTCUSD","amount":"0.0213471340487465","price":"9300","gid":380076977,"cid":490724839}]
2018-06-06 10:37:19:390 | Debug | Received message: [0,"n",[1528306638317,"on-req",null,null,[13037066208,null,490724839,"tBTCUSD",null,null,0.02134713,0.02134713,"STOP",null,null,null,null,null,null,null,9300,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null],null,"SUCCESS","Submitting stop buy order for 0.02134713 BTC."]]
2018-06-06 10:37:19:390 | Debug | Processing [0,"n",[1528306638317,"on-req",null,null,[13037066208,null,490724839,"tBTCUSD",null,null,0.02134713,0.02134713,"STOP",null,null,null,null,null,null,null,9300,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null],null,"SUCCESS","Submitting stop buy order for 0.02134713 BTC."]]
2018-06-06 10:37:19:420 | Debug | Received message: [0,"on",[13037066208,380076977,490724839,"tBTCUSD",1528306638298,1528306638318,0.02134713,0.02134713,"STOP",null,null,null,0,"ACTIVE",null,null,9300,0,null,null,null,null,null,0,0,0,null,null,"API>BFX",null,null,null]]
2018-06-06 10:37:19:421 | Debug | Processing [0,"on",[13037066208,380076977,490724839,"tBTCUSD",1528306638298,1528306638318,0.02134713,0.02134713,"STOP",null,null,null,0,"ACTIVE",null,null,9300,0,null,null,null,null,null,0,0,0,null,null,"API>BFX",null,null,null]]
2018-06-06 10:37:20:233 | Debug | Received message: [2,"te",[254542478,1528306639112,-0.005,7530.4]]
2018-06-06 10:37:20:234 | Debug | Processing [2,"te",[254542478,1528306639112,-0.005,7530.4]]
2018-06-06 10:37:20:266 | Debug | Received message: [2,"tu",[254542478,1528306639112,-0.005,7530.4]]
2018-06-06 10:37:20:266 | Debug | Processing [2,"tu",[254542478,1528306639112,-0.005,7530.4]]
2018-06-06 10:37:21:829 | Debug | Received message: [2,"te",[254542490,1528306640704,1,7530.5]]
2018-06-06 10:37:21:830 | Debug | Processing [2,"te",[254542490,1528306640704,1,7530.5]]
2018-06-06 10:37:21:830 | Debug | Received message: [2,"tu",[254542490,1528306640704,1,7530.5]]
2018-06-06 10:37:21:851 | Debug | Processing [2,"tu",[254542490,1528306640704,1,7530.5]]
2018-06-06 10:37:23:793 | Debug | Received message: [2,"hb"]
2018-06-06 10:37:23:794 | Debug | Processing [2,"hb"]

**Comment by ciottied** [comment] 2018-06-07 13:36
Same problem here.
Rare but at times no orderID returned, but bitfinex accepts the order (sending with v2 websocket async).

**Comment by JKorf** [comment] 2018-06-11 07:56
Hi, this should be resolved in the latest release. The problem was that the order returned gets matched on the Amount property. If you send more than 8 decimals Bitfinex will round it to 8 decimals and the amound send will not be the exact same as the amount returned. I've added a check this and it should match now.

**Closed by JKorf** 2018-06-11 07:56 UTC
